# docker-compose.yml
version: '3'
services:
    app:
        build: .
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://postgres@postgres:5432/table_hub
            NODE_ENV: development
            PORT: 4444
        ports:
            - '4444:4444'
        command: npm run dev
        volumes:
            - .:/app/
            - /app/node_modules

    postgres:
        image: postgres:10.4
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD:
            POSTGRES_DB: table_hub
